"use client";
import { FormEvent, useState } from "react";

const departments=["Keimanan & Ketaqwaan Tuhan YME","Budi Pekerti Luhur & Karakter Vokasi","Wawasan Kebangsaan & Bela Negara","Prestasi Akademik, Riset & Vokasi","Demokrasi, HAM & Lingkungan Hidup","Kreativitas & Kewirausahaan Siswa","Jasmani, Kesehatan & Olahraga Prestasi","Apresiasi Seni & Multimedia Cyber"];
const priorities=["Digitalisasi Layanan Kesiswaan & Portofolio","Bodoet Vocational Cup & Gebyar LKS se-DKI","Green Campus Budi Utomo & Bakti Sosial Industri"];
const calendar=[["Okt – Nov 2024","LDKS Taruna Tangguh","Latihan Dasar Kepemimpinan Siswa"],["Desember 2024","Gelar Karya P5 & Bazar Kewirausahaan","Pameran proyek rekayasa teknologi"],["Februari 2025","Bodoet Vocational Cup VII","Pekan kompetisi futsal"],["Mei – Juni 2025","E-Piketos Raya & Musyawarah MPK","Sidang umum laporan pertanggungjawaban"]];
export function OrganizationDesignedPage(){
 const [status,setStatus]=useState("");
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus("Aspirasi tersimpan hanya sebagai pratinjau di halaman ini dan tidak dikirim.");}
 return <div className="reference-subpage osis-design-page">
  <div className="osis-meta reference-wrap"><span>▣ SK KASEK NO. 421/85/008/SMKN1/X/2024</span><b>Masa Bakti 2024/2025</b></div>
  <section className="osis-design-hero reference-wrap"><small>STRUKTUR ORGANISASI OSIS &amp; MPK</small><h1>STRUKTUR <em>ORGANISASI</em></h1><p>Bagan Hierarki Pembinaan Kesiswaan, Musyawarah Perwakilan Kelas (MPK), dan Pengurus Inti Organisasi Siswa Intra Sekolah (OSIS) SMKN 1 Jakarta (Budi Utomo) Masa Bakti 2024/2025.</p><nav><a href="#organization-chart">☷ Eksplorasi Bagan Interaktif</a><a href="#aspirations">▧ Kotak Aspirasi Digital</a><a href="#documents">⇩ Unduh AD/ART &amp; LPJ</a></nav></section>
  <section className="osis-metrics reference-wrap">{[["64","SISWA PENGURUS TERPILIH · MPK & OSIS TERPADU"],["8","SEKSI BIDANG PELAKSANA"],["18","EKSTRAKURIKULER AKTIF"],["100%","SINERGI DUNIA INDUSTRI"]].map(([n,t])=><article key={t}><b>{n}</b><span>{t}</span></article>)}</section>
  <section className="osis-chart" id="organization-chart"><div className="reference-wrap"><header><small>◈ BAGAN KOMANDO &amp; KOORDINASI</small><h2>Hierarki Kepemimpinan Organisasi</h2><p>Peta relasi institusional dari Pimpinan Sekolah hingga Seksi Bidang Pelaksana Teknis.</p></header><div className="osis-org-tree"><article className="osis-principal"><small>PENANGGUNG JAWAB UMUM</small><b>KEPALA SMKN 1 JAKARTA</b><span>Dr. H. Mulyadi, M.Pd.</span></article><div className="osis-leaders"><article><small>PEMBINA TEKNIS</small><b>Wakasek Bidang Kesiswaan</b><span>Dra. Sri Rahayu, M.M.</span></article><article><small>BADAN LEGISLATIF &amp; ASPIRASI</small><b>Ketua Umum MPK</b><span>Reyhan Pratama · XI Teknik Otomasi</span></article></div><article className="osis-president"><small>MANDATARIS TARUNA</small><b>FARIS AL-GHIFARI</b><span>Ketua Umum OSIS SMKN 1 Jakarta · 2024–2025</span></article><div className="osis-departments">{departments.map((item,i)=><article key={item}><small>0{i+1}</small><span>♧</span><h3>{item}</h3><p>Koord: Pengurus OSIS Terpilih</p><div><i>Program bidang</i><i>Rencana kerja tahunan</i></div></article>)}</div></div></div></section>
  <section className="osis-priorities"><div className="reference-wrap"><aside><small>PIMPINAN TERPILIH 2024/2025</small><h2>Faris Al-Ghifari</h2><p>Ketua Umum OSIS Terpilih · Masa bakti 2024/2025</p><blockquote>“Mewujudkan OSIS SMKN 1 Jakarta yang Sinergis, Berdaya Saing Industri, dan Berintegritas.”</blockquote></aside><div><small>ARAH KEBIJAKAN OSIS</small><h2>Tiga Pilar Program Prioritas Taruna</h2><p>Transformasi tata kelola kesiswaan berbasis vokasi terintegrasi.</p>{priorities.map((item,i)=><article key={item}><b>0{i+1}</b><h3>{item}</h3><p>{["Membangun sistem arsip digital proposal ekskul, presensi, dan portofolio kegiatan siswa.","Menyelenggarakan kompetisi vokasi tingkat antar-SMK se-DKI Jakarta.","Gerakan pemilahan limbah bengkel dan program penanaman pohon."][i]}</p></article>)}</div></div></section>
  <section className="osis-calendar reference-wrap"><header><small>◷ ROADMAP TAHUNAN</small><h2>Kalender Program Kerja OSIS 2024/2025</h2><p>Agenda terstruktur pembinaan karakter, kompetensi keahlian, dan peringatan hari besar kebangsaan.</p></header><div>{calendar.map(([date,title,body],i)=><article key={title}><small>{date}</small><b>{title}</b><p>{body}</p><span>Status: {i===0?"Selesai 100%":"Rencana kerja"}</span></article>)}</div></section>
  <section className="osis-forms reference-wrap"><form id="aspirations" onSubmit={submit}><small>KOTAK SUARA TARUNA DIGITAL</small><h2>Sampaikan Aspirasi Anda</h2><p>Sampaikan saran, gagasan kegiatan sekolah, atau kritik fasilitas langsung ke MPK &amp; OSIS.</p><div><label>Nama Lengkap (Opsional)<input placeholder="Bisa dikosongkan (Anonim)" /></label><label>Kelas &amp; Jurusan<select defaultValue=""><option value="" disabled>Pilih Tingkat &amp; Konsentrasi...</option><option>XI · Teknik</option><option>X · Teknik</option></select></label><label>Kategori Aspirasi<select defaultValue=""><option value="" disabled>Pilih kategori...</option><option>Fasilitas</option><option>Kegiatan</option><option>Akademik</option></select></label><label>Tujuan Rekomendasi<select defaultValue=""><option>Pengurus Harian OSIS</option><option>MPK</option></select></label><label className="osis-message">Uraian Gagasan / Masukan / Pengaduan<textarea required minLength={8} placeholder="Tuliskan aspirasi secara rinci..." /></label></div><button type="submit">➤ Kirim Aspirasi</button>{status&&<p role="status">{status}</p>}</form>
   <aside id="documents"><small>REPOSITORI ADMINISTRASI</small><h2>Dokumen &amp; Template Resmi OSIS</h2><p>Unduh berkas administrasi keorganisasian sesuai prosedur.</p>{["AD / ART OSIS SMKN 1 Jakarta","Format Standar Proposal Ekskul","Template Laporan Pertanggungjawaban (LPJ)","Pakta Integritas Taruna Budi Utomo"].map((doc)=><button type="button" key={doc} disabled title="Berkas sumber tidak tersedia">{doc} <span>Dokumen belum tersedia</span></button>)}</aside></section>
 </div>;
}
