import Image from "next/image";
import Link from "next/link";
import { CmsFeedCards } from "@/components/CmsFeedCards";
import type { CmsPublicFeed } from "@/lib/cms-public";
import { publicSections } from "@/lib/public-sections";

const Arrow = () => <span aria-hidden="true">↗</span>;
const Photo = ({ src, alt }: { src: string; alt: string }) => <div className="reference-photo"><Image src={src} alt={alt} fill sizes="(max-width: 700px) 90vw, 30vw" /></div>;
const DataNote = ({ children }: { children: React.ReactNode }) => <p className="reference-data-note"><span>DATA BELUM TERSEDIA</span>{children}</p>;

export function ProgramReferencePage() {
  const programs = publicSections.tentang.blocks.find((block) => block.id === "program")?.cards ?? [];
  const awards = publicSections.kegiatan.blocks.find((block) => block.id === "prestasi")?.cards ?? [];
  const images = ["program-rpl-photo.png", "program-tkj-photo.png", "program-tkr-photo.png", "program-toi-photo.png"];
  return <div className="reference-subpage reference-program-page">
    <section className="reference-program-hero reference-wrap"><div><small>PROGRAM KEAHLIAN · INFORMASI SEKOLAH</small><h1>{programs.length} Nama Kompetensi<br /><em>dalam Arsip Sekolah</em></h1><p>Daftar ini merujuk arsip tahun ajaran 2022/2023. Ketersediaan program pada tahun ajaran berjalan belum dikonfirmasi.</p><div className="reference-hero-actions"><Link href="#reference-program-list">Jelajahi arsip <Arrow /></Link><Link href="/kontak">Hubungi sekolah <Arrow /></Link></div></div><div className="reference-program-seal"><Image src="/logo-sekolah.png" alt="" width={70} height={78} /><span>ARSIP<br />2022/2023</span></div></section>
    <section className="reference-intro-block reference-wrap"><div><small>PROGRAM KEAHLIAN</small><h2>Kompetensi<br /><em>kejuruan.</em></h2></div><div><h3>Daftar program sebagaimana tercantum dalam arsip sekolah.</h3><p>Nama dan status terkini perlu dikonfirmasi langsung melalui kanal resmi sekolah. Kartu berikut mempertahankan nama dari sumber yang telah ditinjau.</p><div className="reference-mini-facts"><span><b>{programs.length}</b> nama arsip</span><span><b>2022/2023</b> tahun sumber</span><span><b>—</b> status tahun berjalan</span></div></div></section>
    <section className="reference-toolkit-section"><div className="reference-wrap"><header className="reference-section-heading"><div><small>FASILITAS &amp; SERTIFIKASI</small><h2>Toolkit &amp; fasilitas<br />pembelajaran</h2></div></header><DataNote>Informasi fasilitas, perangkat, lisensi, dan sertifikasi tiap program belum tersedia pada sumber sekolah yang ditinjau.</DataNote><div className="reference-toolkit-grid">{["Perangkat pembelajaran", "Laboratorium dan bengkel", "Sertifikasi kompetensi", "Mitra industri"].map((label, i) => <article key={label}><span>0{i + 1}</span><h3>{label}</h3><p>[DATA BELUM TERSEDIA]</p></article>)}</div></div></section>
    <section className="reference-program-list reference-wrap" id="reference-program-list"><header className="reference-section-heading"><div><small>ARSIP KOMPETENSI KEAHLIAN</small><h2>Program keahlian</h2><p>Nama pada arsip; status aktif belum dikonfirmasi.</p></div><span className="reference-count-pill">{programs.length} arsip</span></header><div className="reference-program-grid">{programs.map((program, index) => <article className="reference-program-card" key={program.title}><Photo src={`/images/reference/${images[index % images.length]}`} alt="Ilustrasi kegiatan pembelajaran vokasi" /><div className="reference-program-body"><small>ARSIP TA 2022/2023</small><h3>{program.title}</h3><p>{program.description}</p><Link href="/kontak">Tanyakan status program <Arrow /></Link></div></article>)}</div></section>
    <section className="reference-awards"><div className="reference-wrap"><header><div><small>CATATAN DENGAN TAHUN SUMBER</small><h2>Selected<br /><em>achievements.</em></h2></div><p>Prestasi berikut ditampilkan sebagai arsip. Tahun yang tercantum bukan penanda capaian terbaru.</p></header><div className="reference-award-list">{awards.slice(0, 4).map((award, i) => <article key={award.title + i}><span>0{i + 1}</span><strong>{award.title}</strong><p>{award.description}</p><small>{award.label}</small></article>)}</div><p className="reference-award-footnote">Arsip prestasi sekolah · Tahun dan kategori sesuai sumber.</p></div></section>
    <section className="reference-contact-cta"><div className="reference-wrap"><div><small>INFORMASI PROGRAM</small><h2>Perlu memastikan status<br />program keahlian?</h2><p>Hubungi sekolah melalui informasi kontak yang tersedia.</p></div><Link href="/kontak">Informasi kontak <Arrow /></Link></div></section>
  </div>;
}

export function StudentLifeReferencePage() {
  const activities = publicSections.kesiswaan.blocks;
  const awards = publicSections.kegiatan.blocks.find((block) => block.id === "prestasi")?.cards ?? [];
  return <div className="reference-subpage">
    <div className="reference-subnav"><div className="reference-wrap"><span>KESISWAAN</span><Link href="/osis">Organisasi OSIS <Arrow /></Link><Link href="/kegiatan#prestasi">Arsip prestasi <Arrow /></Link></div></div>
    <section className="reference-student-hero"><div className="reference-wrap"><div><small>KEHIDUPAN SISWA</small><h1>Mengembangkan potensi<br />dan karakter siswa</h1><p>Informasi organisasi, kegiatan, dan prestasi ditampilkan berdasarkan data yang tersedia dari sumber sekolah.</p><Link href="#student-activities">Lihat informasi kesiswaan <Arrow /></Link></div><div className="reference-student-highlight"><span>ARSIP PRESTASI</span><strong>{awards.length}</strong><small>catatan prestasi bertahun</small><Photo src="/images/reference/program-toi-photo.png" alt="Suasana pembelajaran di sekolah" /></div></div></section>
    <section className="reference-stat-strip"><div className="reference-wrap">{["Unit ekstrakurikuler", "Medali dan piala", "Capaian tingkat nasional", "Ajang internasional"].map((name) => <article key={name}><strong>—</strong><span>{name}</span></article>)}</div></section>
    <section className="reference-student-values reference-wrap"><header><small>LANDASAN &amp; FILOSOFI PEMBINAAN</small><h2>Mendampingi potensi<br /><em>dan minat siswa.</em></h2><p>Rincian pembinaan organisasi dan ekstrakurikuler belum tersedia di repository.</p></header><div className="reference-student-card-grid">{activities.slice(0, 3).map((activity, i) => <article key={activity.id}><span>0{i + 1} / INFORMASI</span><h3>{activity.title}</h3><p>{activity.body ?? "Informasi belum tersedia."}</p><DataNote>[DATA BELUM TERSEDIA]</DataNote><Link href={activity.id === "prestasi" ? "/kegiatan#prestasi" : "/osis"}>Lihat informasi <Arrow /></Link></article>)}</div></section>
    <section className="reference-activity-section" id="student-activities"><div className="reference-wrap"><header className="reference-section-heading"><div><small>KEGIATAN &amp; PENGEMBANGAN DIRI</small><h2>Eksplorasi minat<br />dan bakat.</h2><p>Daftar kegiatan dan jadwal terbit akan ditambahkan setelah informasinya tersedia.</p></div><Link href="/kontak">Tanyakan ke sekolah <Arrow /></Link></header><DataNote>Daftar ekstrakurikuler, jadwal, pembina, dan alur pendaftaran belum tersedia pada sumber yang ditinjau.</DataNote></div></section>
    <section className="reference-awards"><div className="reference-wrap"><header><div><small>ARSIP PRESTASI</small><h2>Selected<br /><em>achievements.</em></h2></div><p>Catatan capaian dengan tahun sebagaimana tercantum pada sumber resmi.</p></header><div className="reference-award-list">{awards.slice(0, 5).map((award, i) => <article key={award.title + i}><span>0{i + 1}</span><strong>{award.title}</strong><p>{award.description}</p><small>{award.label}</small></article>)}</div></div></section>
  </div>;
}

export function OrganizationReferencePage() {
  const areas = ["Internal & disiplin", "Eksternal & kemitraan", "Administrasi & notula", "Anggaran & keuangan"];
  return <div className="reference-subpage reference-organization"><div className="reference-subnav"><div className="reference-wrap"><Link href="/kesiswaan">← Kembali ke kesiswaan</Link><span>ORGANISASI SISWA</span></div></div>
    <section className="reference-osis-hero reference-wrap"><small>STRUKTUR ORGANISASI · MPK &amp; OSIS</small><h1>Struktur <em>Organisasi</em></h1><p>Informasi struktur, pengurus, dan masa bakti organisasi siswa.</p><div className="reference-osis-actions"><button type="button" disabled>Bagan organisasi belum tersedia</button><button type="button" disabled>Dokumen organisasi belum tersedia</button></div></section>
    <section className="reference-osis-stats reference-wrap">{["Siswa pengurus terpilih", "Seksi bidang", "Ekstrakurikuler aktif", "Sinergi industri"].map((item) => <article key={item}><strong>—</strong><span>{item}</span></article>)}</section>
    <section className="reference-organization-chart reference-wrap"><header><small>BAGAN KOMANDO &amp; KOORDINASI</small><h2>Hierarki kepemimpinan organisasi</h2><p>Data pengurus dan struktur organisasi belum tersedia.</p></header><div className="reference-org-tree"><div className="reference-org-root"><small>PENANGGUNG JAWAB UMUM</small><strong>[DATA BELUM TERSEDIA]</strong><span>Kepala sekolah</span></div><div className="reference-org-branch"><article><small>PEMBINA ORGANISASI</small><strong>[DATA BELUM TERSEDIA]</strong><span>Wakasek bidang terkait</span></article><article><small>BADAN PERWAKILAN</small><strong>[DATA BELUM TERSEDIA]</strong><span>Pengurus MPK</span></article></div><div className="reference-org-leader"><small>MANDATARIS SISWA</small><strong>[DATA BELUM TERSEDIA]</strong><span>Ketua OSIS dan pengurus</span></div><div className="reference-org-departments">{areas.map((area, i) => <article key={area}><span>0{i + 1}</span><h3>{area}</h3><p>Rincian bidang belum tersedia.</p></article>)}</div></div></section>
    <section className="reference-osis-programs"><div className="reference-wrap"><header><small>ARAH KEGIATAN ORGANISASI</small><h2>Program kerja siswa</h2><p>Program dan kalender organisasi akan ditampilkan setelah diterbitkan secara resmi.</p></header><DataNote>Program prioritas, kalender kegiatan, serta dokumen organisasi belum tersedia pada data repository.</DataNote></div></section>
    <section className="reference-osis-contact reference-wrap"><div><small>KOTAK SUARA DIGITAL</small><h2>Sampaikan aspirasi</h2><p>Form aspirasi belum terhubung ke layanan sekolah. Gunakan halaman kontak untuk melihat kanal resmi yang tersedia.</p><Link href="/kontak">Buka informasi kontak <Arrow /></Link></div><div><small>REPOSITORI DOKUMEN</small><h2>Dokumen organisasi</h2><p>[DATA BELUM TERSEDIA]</p></div></section>
  </div>;
}

export function InformationReferencePage({ feeds }: { feeds: Partial<Record<"news" | "announcements" | "academic-agenda", CmsPublicFeed>> }) {
  const news = feeds.news;
  const announcements = feeds.announcements;
  const archived = publicSections.informasi.blocks.find((block) => block.id === "arsip-situs-resmi")?.cards ?? [];
  return <div className="reference-subpage reference-information"><section className="reference-news-hero reference-wrap"><article><small>PENGUMUMAN &amp; PENERIMAAN</small><h1>Berita dan informasi<br />SMK Negeri 1 Jakarta</h1><p>Pengumuman dan agenda yang diterbitkan melalui CMS sekolah tampil di halaman ini.</p><Link href="/ppdb">Informasi PPDB <Arrow /></Link></article><aside><small>PENGUMUMAN SEKOLAH</small>{announcements?.items.slice(0, 3).map((item) => <article key={item.id}><span>CMS SEKOLAH</span><h2>{item.title}</h2></article>)}{(!announcements?.items.length) && <p>Belum ada pengumuman yang diterbitkan.</p>}<Link href="/ppdb">Informasi penerimaan <Arrow /></Link></aside></section>
    <section className="reference-news-list"><div className="reference-wrap"><header><small>WARTA SEKOLAH</small><h2>Kabar &amp; Warta Terkini</h2><p>Berita terbaru yang diterbitkan melalui CMS sekolah.</p></header>{news?.available && news.items.length ? <CmsFeedCards resource="news" items={news.items.slice(0, 4)} /> : <DataNote>{news?.configured ? "Berita sementara tidak dapat dimuat." : "Belum ada berita yang diterbitkan melalui CMS sekolah."}</DataNote>}</div></section>
    <section className="reference-awards"><div className="reference-wrap"><header><div><small>ARSIP SITUS SEKOLAH</small><h2>Berita<br /><em>terdokumentasi.</em></h2></div><p>Artikel berikut ditampilkan sebagai arsip sesuai tanggal dan judul pada sumber.</p></header><div className="reference-award-list">{archived.map((item, i) => <article key={item.href ?? item.title}><span>0{i + 1}</span><strong>{item.title}</strong><p>{item.description}</p><small>{item.label}</small></article>)}</div></div></section>
    <section className="reference-contact-cta"><div className="reference-wrap"><div><small>PUSAT INFORMASI</small><h2>Perlu bantuan informasi?</h2><p>Gunakan kanal kontak sekolah yang tercantum pada halaman kontak.</p></div><Link href="/kontak">Hubungi sekolah <Arrow /></Link></div></section></div>;
}

export function PpdbReferencePage() {
  return <div className="reference-subpage reference-ppdb"><section className="reference-ppdb-top reference-wrap"><article><small>PENERIMAAN MURID BARU</small><h1>Informasi SPMB<br /><em>SMK Negeri 1 Jakarta</em></h1><p>SPMB mengikuti kebijakan dan jadwal resmi Pemerintah Provinsi DKI Jakarta. Portal tahun ajaran 2026/2027 mencantumkan SMK Negeri 1 Jakarta dengan 10 kompetensi. Periksa langsung portal untuk daftar, kuota, persyaratan, dan jadwal terkini.</p><a href="https://spmb.jakarta.go.id/040401/pagu" target="_blank" rel="noreferrer">Buka Portal SPMB DKI Jakarta <Arrow /></a></article><aside><small>TAHUN AJARAN</small><strong>2026/2027</strong><p>Portal resmi SPMB DKI Jakarta.</p></aside></section>
    <section className="reference-ppdb-content reference-wrap"><div><small>JADWAL, JALUR &amp; DOKUMEN</small><h2>Periksa ketentuan resmi</h2><p>Jalur seleksi, persyaratan, tata cara pendaftaran, kuota per program, dan tanggal pengumuman dapat berubah setiap tahun. Gunakan informasi terbaru pada portal resmi.</p><a href="https://spmb.jakarta.go.id/040401/pagu" target="_blank" rel="noreferrer">Lihat pagu dan kompetensi SPMB <Arrow /></a></div><div><small>INFORMASI SEKOLAH</small><h2>Perlu bantuan?</h2><p>Hubungi SMK Negeri 1 Jakarta melalui kanal kontak resmi.</p><Link href="/kontak">Telepon dan email sekolah <Arrow /></Link></div></section>
  </div>;
}
