"use client";
import { FormEvent, useState } from "react";
import Image from "next/image";
import Link from "next/link";

const clubs = [
  { name: "Robotika & Cyber IoT Club", category: "Sains & Teknologi Terapan", image: "/images/reference/program-toi-photo.png", detail: "Fokus pada perancangan mikrokontroler, robot cerdas, automasi, dan kompetisi sains.", schedule: "Rabu & Sabtu, 14.30 – 17.30 WIB" },
  { name: "Paskibra (Satuan Bhakti) 01", category: "Bela Negara & Disiplin", image: "/images/reference/campus.png", detail: "Korp baris-berbaris kehormatan taruna. Menempa kedisiplinan mental, jiwa kepemimpinan, patriotisme, dan formalitas kenegaraan.", schedule: "Selasa & Kamis, 15.00 – 17.00 WIB" },
  { name: "Futsal Bodoet Knights", category: "Olahraga & Atletik", image: "/images/reference/campus.png", detail: "Klub olahraga kebanggaan dengan pembinaan intensif tiap pekan, latihan taktik, dan kompetisi antar sekolah.", schedule: "Senin & Kamis, 16.00 – 18.00 WIB" },
  { name: "Web & Interactive Game Dev", category: "Sains & Teknologi Terapan", image: "/images/reference/program-rpl-photo.png", detail: "Inkubator peningkatan kecakapan anak muda dalam full-stack web, gim interaktif, serta budaya open source.", schedule: "Rabu, 14.30 – 17.30 WIB" },
  { name: "Broadcasting & Sinematografi", category: "Seni & Multimedia Kreatif", image: "/images/reference/program-tkj-photo.png", detail: "Memproduksi konten siaran video sekolah dan liputan kegiatan menggunakan peralatan studio.", schedule: "Jumat, 14.30 – 17.00 WIB" },
  { name: "Pramuka Gudep 01.077 – 01.078", category: "Kerohanian & Karakter", image: "/images/reference/campus.png", detail: "Pendidikan kepanduan untuk pembentukan karakter, kemandirian, serta bakti sosial warga kota.", schedule: "Jumat, 14.00 – 17.00 WIB" }
];
const awards = [
  ["JUARA 1", "LKS Nasional Bidang Cyber Security & Cloud Computing", "Perumusan keamanan terenkripsi tingkat nasional."],
  ["JUARA 1", "Robotics & IoT Competition – GLITER JAK", "Kreasi robotika otonom dan vision intelligence."],
  ["JUARA 1", "Paskibra Invitational Trophy Bergilir Gubernur DKI Jakarta", "Prestasi baris-berbaris dan kepemimpinan."],
  ["MEDALI EMAS", "Pencak Silat Pelajar O2SN Kelas F Putra", "Prestasi gemilang tingkat nasional."],
  ["JUARA 2", "Lomba Inovasi Teknologi Tepat Guna (TTG) Vokasi Nasional", "Inovasi teknologi hasil karya taruna."],
];
const filters = ["Semua Bidang (8)", "Sains & Teknologi Terapan (3)", "Bela Negara & Disiplin (1)", "Olahraga & Atletik (4)", "Seni & Multimedia Kreatif (5)", "Kerohanian & Karakter (2)"];

export function StudentLifeDesignedPage() {
  const [selected, setSelected] = useState(filters[0]);
  const [formStatus, setFormStatus] = useState("");
  const activeCategory = selected.replace(/ \(.*\)$/, "");
  const shown = selected === filters[0] ? clubs : clubs.filter((club) => club.category === activeCategory);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setFormStatus("Pratinjau formulir selesai. Klaim tidak dikirim atau disimpan."); }
  return <div className="reference-subpage student-design-page">
    <div className="student-subbar"><div className="reference-wrap"><span>Ekstrakurikuler</span><a href="#club-catalogue">◉ Open Recruitment TP 2025/2026 Aktif</a><span>Pusat Pembinaan Taruna Vokasi Budi Utomo</span></div></div>
    <section className="student-design-hero"><div className="reference-wrap"><div><small>◈ DIREKTORI BAKAT, KEDISIPLINAN &amp; KEWIRAUSAHAAN VOKASI</small><h1>Membentuk Karakter Tangguh,<br />Merajai Panggung Kompetisi Global</h1><p>Wadah pengembangan minat bakat 18 ekstrakurikuler unggulan SMKN 1 Jakarta (Bodoet). Dari riset rekayasa robotika industri, baris-berbaris disiplin militer, hingga kejuaraan atletik DKI Jakarta.</p><a href="#club-catalogue">◉ Jelajahi 18 Ekskul</a><Link href="#claim-form">Input Sertifikat Siswa</Link></div><div className="student-design-highlight"><strong>142+</strong><span>Medali &amp; Piala (2023–2025)</span></div></div></section>
    <section className="reference-stat-strip"><div className="reference-wrap">{[["18","UNIT EKSTRAKURIKULER"],["48","MEDALI DKI JAKARTA"],["24","JUARA NASIONAL / LKS/OSN"],["04","AJANG INTERNASIONAL"]].map(([n,t])=><article key={t}><strong>{n}</strong><span>{t}</span></article>)}</div></section>
    <section className="reference-student-values reference-wrap"><header><small>◈ LANDASAN &amp; FILOSOFI PEMBINAAN</small><h2>Latar Belakang Pembinaan Ekstrakurikuler Taruna</h2><p>Di SMKN 1 Jakarta (Bodoet), kegiatan ekstrakurikuler bukan sekadar pengisi waktu luang. Ekskul dirancang terstruktur sebagai kawah candradimuka pembentukan karakter industri 4.0, penguatan kedisiplinan mental, pengembangan jiwa kepemimpinan, dan akselerator talenta unggul.</p></header><div className="student-design-principles">{["Integrasi Nilai Budaya Kerja Industri (5R & K3LH)","Penyaluran Bakat & Prevensi Dekadensi Remaja","Inkubasi Talenta Menuju Panggung Global","Rekognisi Portofolio & Golden Ticket BKK"].map((title,i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{["Menanamkan etos kerja tinggi, resik, rapi, ketepatan waktu, dan kepatuhan SOP industri.","Menjembatani energi remaja ke aktivitas positif yang membangun kompetensi vokasi.","Mengembangkan talenta kompetisi vokasi dengan persiapan terstruktur dan mentoring.","Setiap pencapaian menjadi bahan prestasi dan portofolio bagi dunia industri."][i]}</p></article>)}</div></section>
    <section className="student-design-banner"><div className="reference-wrap"><b>◈ LANDASAN REGULASI &amp; KOMITMEN MANAJEMEN KESISWAAN</b><p>Berdasarkan Permendikbudristek No. 62 Tahun 2014 tentang Kegiatan Ekstrakurikuler pada Pendidikan Dasar dan Menengah serta Surat Keputusan Kepala Dinas Pendidikan Provinsi DKI Jakarta tentang Penguatan Pendidikan Vokasi.</p></div></section>
    <section className="reference-activity-section" id="club-catalogue"><div className="reference-wrap"><header className="reference-section-heading"><div><small>KATALOG EKSTRAKURIKULER TARUNA</small><h2>Eksplorasi Minat, Asah Keahlian Vokasi</h2><p>Setiap peserta didik wajib memilih minimal 1 kegiatan pengembangan diri untuk memperkuat portofolio kejuruan, kepemimpinan, dan kesejahteraan jasmani.</p></div><button className="reference-reset" onClick={()=>setSelected(filters[0])}>↻ Reset Filter</button></header><div className="student-design-filters">{filters.map((filter)=><button type="button" key={filter} aria-pressed={selected===filter} onClick={()=>setSelected(filter)}>{filter}</button>)}</div><div className="student-club-grid">{shown.map((club)=><article key={club.name}><div className="student-club-photo"><Image src={club.image} alt="" fill sizes="(max-width: 700px) 90vw, 33vw" /></div><small>{club.category.toUpperCase()}</small><h3>{club.name}</h3><p>{club.detail}</p><span>◷ {club.schedule}</span><button type="button" onClick={()=>setFormStatus("Informasi pendaftaran ditampilkan sebagai pratinjau dan belum dikirim.")}>Daftar Anggota</button></article>)}</div><p className="student-count-note">Menampilkan {shown.length} dari 18 direktori kegiatan ekstrakurikuler resmi SMKN 1 Jakarta</p></div></section>
    <section className="student-design-awards"><div className="reference-wrap"><header><div><small>HALL OF FAME VOKASI SMKN 1 JAKARTA</small><h2>SELECTED<br />ACHIEVEMENTS.</h2></div><p>Ideas tested beyond the classroom. A selection of prestigious national competition milestones and championship records.</p></header><div className="student-achievement-list">{awards.map(([award,title,desc],i)=><article key={title}><small>{String(i+1).padStart(2,"0")}</small><strong>{award}</strong><div><b>{title}</b><p>{desc}</p></div><span>2025 ↗</span></article>)}</div><p>Menampilkan 5 dari 142 data pencatatan kejuaraan resmi SMKN 1 Jakarta</p></div></section>
    <section className="student-claim reference-wrap" id="claim-form"><form onSubmit={submit}><small>◉ PORTAL VALIDASI MANDIRI</small><h2>Formulir Pendataan &amp; Klaim Prestasi Siswa</h2><p>Laporkan sertifikat kejuaraan mandiri/diluar agenda resmi sekolah agar terverifikasi ke dalam sistem nilai rapor SINDARA DKI.</p><div className="contact-form-two-col"><label>Nama Lengkap<input required placeholder="Contoh: Muhammad Fikri Pratama" /></label><label>Nomor Induk Siswa Nasional (NISN)<input required placeholder="Nomor induk siswa nasional" /></label><label>Kelas &amp; Program Keahlian<input required placeholder="Pilih program keahlian..." /></label><label>Tingkat Penyelenggaraan<input required placeholder="Tingkat Kota/Wilayah Jakarta Pusat" /></label><label>Nama Kompetisi &amp; Lembaga Penyelenggara<input required placeholder="Contoh: Lomba Inovasi Vokasi 2025" /></label><label>Tanggal Kejuaraan<input type="date" required /></label><label className="student-upload">Unggah Dokumen Sertifikat &amp; Dokumentasi<input type="file" accept=".pdf,.jpg,.jpeg,.png" /></label></div><button type="submit">➤ Kirim Verifikasi Prestasi</button>{formStatus && <p role="status">{formStatus}</p>}</form></section>
  </div>;
}
